<h3>Linear Regression Model</h3>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Importing the datasets
datasets = pd.read_csv('Data.csv')
X = datasets.iloc[:, :1].values
Y = datasets.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.4, random_state = 2)

# Fitting Simple Linear Regression to the training set
regressor = LinearRegression()
regressor.fit(X_Train, Y_Train)

# Predicting the Test set result 
Y_Pred = regressor.predict(X_Test)

#Calculating SSE
sse = np.sum((Y_Test - Y_Pred)**2)
print("SSE =",sse)

#Calculating SST
Y_mean = np.mean(Y_Test)
sst = np.sum((Y_Test - Y_mean)**2)
print("SST =",sst)

#Calculating R^2
R_sq = 1-(sse/sst)
print("R^2 =",R_sq)
print()

#Calculation of Regression Coefficients
arr = [[1],[1],[1],[1],[1],[1],[1],[1],[1],[1]]
X_fin = np.append(arr,X,axis = 1)
print(X_fin)
print()
X_trans = np.transpose(X_fin)
print(X_trans)
print()
XX = np.dot(X_trans,X_fin)
print(XX)
print()
Inv = np.linalg.inv(XX)
print(Inv)
print()
nw = np.matmul(X_trans,Y)
res = np.matmul(Inv,nw)
print(res)

SSE = 10035267.608938847
SST = 63167102.0
R^2 = 0.8411314229844066

[[  1  12]
 [  1  23]
 [  1  34]
 [  1  45]
 [  1  56]
 [  1  67]
 [  1  78]
 [  1  89]
 [  1 123]
 [  1 134]]

[[  1   1   1   1   1   1   1   1   1   1]
 [ 12  23  34  45  56  67  78  89 123 134]]

[[   10   661]
 [  661 58569]]

[[ 3.93690890e-01 -4.44312995e-03]
 [-4.44312995e-03  6.72183049e-05]]

[-3354.93363537   190.53000961]


<h3>Polynomial Regression Model(Degree 2)</h3>

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

#importing datasets
datasets = pd.read_csv('Data.csv')
X = datasets.iloc[:,:-1].values
Y = datasets.iloc[:,-1].values

#transforming input data
transformer = PolynomialFeatures(degree = 2)
transformer.fit(X)
X_ = transformer.transform(X)

#creating a model
model = LinearRegression()
model.fit(X_,Y)

#Predicting the result
Y_Pred = model.predict(X_)

#Calculating SSE
sse = np.sum((Y - Y_Pred)**2)
print("SSE =",sse)

#Calculating SST
Y_mean = np.mean(Y)
sst = np.sum((Y - Y_mean)**2)
print("SST =",sst)

#Calculating R^2
R_sq = 1-(sse/sst)
print("R^2 =",R_sq)
print()

#Calculation of Regression coefficients

X_trans = np.transpose(X_)
print(X_trans)
print()
XX = np.dot(X_trans,X_)
print(XX)
print()
Inv = np.linalg.inv(XX)
print(Inv)
print()
nw = np.matmul(X_trans,Y)
res = np.matmul(Inv,nw)
print(res)


SSE = 7376814.381379519
SST = 550026500.9
R^2 = 0.9865882564398099

[[1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00
  1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00]
 [1.2000e+01 2.3000e+01 3.4000e+01 4.5000e+01 5.6000e+01 6.7000e+01
  7.8000e+01 8.9000e+01 1.2300e+02 1.3400e+02]
 [1.4400e+02 5.2900e+02 1.1560e+03 2.0250e+03 3.1360e+03 4.4890e+03
  6.0840e+03 7.9210e+03 1.5129e+04 1.7956e+04]]

[[1.00000000e+01 6.61000000e+02 5.85690000e+04]
 [6.61000000e+02 5.85690000e+04 6.06719500e+06]
 [5.85690000e+04 6.06719500e+06 6.86785029e+08]]

[[ 1.16699360e+00 -3.37146441e-02  1.98320677e-04]
 [-3.37146441e-02  1.17522107e-03 -7.50695220e-06]
 [ 1.98320677e-04 -7.50695220e-06  5.08611831e-08]]

[-1.93884955e+03  1.36927553e+02  3.63167942e-01]


<h3>Polynomial Regression Model(Degree 3)</h3>

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

#importing datasets
datasets = pd.read_csv('Data.csv')
X = datasets.iloc[:,:-1].values
Y = datasets.iloc[:,-1].values

#transforming input data
transformer = PolynomialFeatures(degree = 3)
transformer.fit(X)
X_ = transformer.transform(X)

#creating a model
model = LinearRegression()
model.fit(X_,Y)

#Predicting the result
Y_Pred = model.predict(X_)

#Calculating SSE
sse = np.sum((Y - Y_Pred)**2)
print("SSE =",sse)

#Calculating SST
Y_mean = np.mean(Y)
sst = np.sum((Y - Y_mean)**2)
print("SST =",sst)

#Calculating R^2
R_sq = 1-(sse/sst)
print("R^2 =",R_sq)
print()

#Calculation of Regression coefficients
arr = [[1],[1],[1],[1],[1],[1],[1],[1],[1],[1]]
X_ = np.append(arr,X,axis = 1)
X__ = np.append(X_,X**2,axis = 1)
X_fin = np.append(X__,X**3,axis = 1)
print(X_fin)
X_trans = np.transpose(X_fin)
print(X_trans)
print()
XX = np.dot(X_trans,X_fin)
print(XX)
print()
Inv = np.linalg.inv(XX)
print(Inv)
print()
nw = np.matmul(X_trans,Y)
res = np.matmul(Inv,nw)
print(res)


SSE = 7201761.797283199
SST = 550026500.9
R^2 = 0.9869065185304725

[[      1      12     144    1728]
 [      1      23     529   12167]
 [      1      34    1156   39304]
 [      1      45    2025   91125]
 [      1      56    3136  175616]
 [      1      67    4489  300763]
 [      1      78    6084  474552]
 [      1      89    7921  704969]
 [      1     123   15129 1860867]
 [      1     134   17956 2406104]]
[[      1       1       1       1       1       1       1       1       1
        1]
 [     12      23      34      45      56      67      78      89     123
      134]
 [    144     529    1156    2025    3136    4489    6084    7921   15129
    17956]
 [   1728   12167   39304   91125  175616  300763  474552  704969 1860867
  2406104]]

[[            10            661          58569        6067195]
 [           661          58569        6067195      686785029]
 [         58569        6067195      686785029    81965799691]
 [       6067195      686785029    81965799691 101